name: pesquisa_cep
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  easy_rich_text: '^2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  fluttertoast: ^8.0.6

flutter:
  uses-material-design: true

